name: Docker publish

concurrency: production

on:
  workflow_dispatch:

env:
  dockerhub_image: hugocker/playwright_runner

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t playwright_runner .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push build images
        run: |
          docker tag playwright_runner $dockerhub_image:build-$GITHUB_RUN_ID
          docker push $dockerhub_image:build-$GITHUB_RUN_ID
      - name: Publish latest
        run: |
          docker tag $dockerhub_image:build-$GITHUB_RUN_ID $dockerhub_image
          docker push $dockerhub_image
